"""add lesson progress

Revision ID: 28072230e793
Revises: 
Create Date: 2026-07-02 07:06:15.707072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28072230e793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_enrollment_lesson', ['enrollment_id', 'lesson_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_constraint('uq_enrollment_lesson', type_='unique')

    # ### end Alembic commands ###
